name:                circle-backend
version:             0.1.0.0
github:              "xiongxiong/circle-backend"
license:             BSD3
author:              "wonderbear"
maintainer:          "ximengwuheng@163.com"
copyright:           "2021 wonderbear"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            exercise

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xiongxiong/circle-backend#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp

library:
  source-dirs: src

executables:
  circle-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - circle-backend

tests:
  circle-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - circle-backend
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
